# Generated by Django 4.1 on 2024-11-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientUpdates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pws',
            options={'managed': True},
        ),
    ]
