# Generated by Django 4.1 on 2024-11-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientUpdates', '0003_alter_pws_row_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eurofinsreportsfilenames',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='flowrate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pfasreportsfilenames',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pfasresult',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productiondatafilenames',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pwsaddress',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pwscontact',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'managed': True},
        ),
    ]
