# Generated by Django 4.1 on 2024-11-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientUpdates', '0004_alter_eurofinsreportsfilenames_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eurofinsreportsfilenames',
            name='row_names',
            field=models.BigAutoField(db_column='row_names', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flowrate',
            name='row_names',
            field=models.BigAutoField(db_column='row_names', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pfasreportsfilenames',
            name='row_names',
            field=models.BigAutoField(db_column='row_names', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pfasresult',
            name='row_names',
            field=models.BigAutoField(db_column='row_names', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productiondatafilenames',
            name='row_names',
            field=models.BigAutoField(db_column='row_names', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pwsaddress',
            name='row_names',
            field=models.BigAutoField(db_column='row_names', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pwscontact',
            name='row_names',
            field=models.BigAutoField(db_column='row_names', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='row_names',
            field=models.BigAutoField(db_column='row_names', primary_key=True, serialize=False),
        ),
    ]
